-- ============================================================
-- SIF-Aegis : Safety Intelligence Layer
-- PostgreSQL + pgvector
-- Run once:  psql -f schema.sql
-- ============================================================
DO $$ BEGIN
  CREATE EXTENSION IF NOT EXISTS vector;
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'pgvector not available - vector search disabled';
END $$;

-- ------------------------------------------------------------
-- 1. CORE REPORT STORE   (raw immutable; analysis regenerable)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reports (
  id                      SERIAL PRIMARY KEY,
  incident_id             TEXT NOT NULL UNIQUE,
  location                TEXT,
  event_date              DATE,
  injury_severity         TEXT,
  raw_text                TEXT NOT NULL,
  summary                 TEXT,
  sif_score               REAL NULL,       -- 0..1, from friend's JSON (may be NULL)
  sif_class               TEXT NULL,       -- LOW | MEDIUM | HIGH
  sif_method              TEXT NULL,       -- scoring method
  sif_weight_source       TEXT NULL,       -- weight source
  sif_components          JSONB,           -- score components breakdown
  analysis_json           JSONB,           -- full NLP analysis JSON (source of truth for derived rows)
  edited_at               TIMESTAMPTZ,     -- when an admin last overrode summary/analysis
  created_at              TIMESTAMPTZ DEFAULT now()
);

-- report-level embedding built from a composed "safety representation"
-- Only if pgvector is available
DO $$ BEGIN
  ALTER TABLE reports ADD COLUMN IF NOT EXISTS embedding VECTOR(384);
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- ------------------------------------------------------------
-- 2. SAFETY ENTITIES   (two taxonomies: behavioral + hazard/iogp)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS precursors (
  id       SERIAL PRIMARY KEY,
  code     TEXT NOT NULL UNIQUE,          -- safe_work_procedure, energy_isolation, ...
  name     TEXT NOT NULL,
  taxonomy TEXT NOT NULL DEFAULT 'behavioral'  -- 'behavioral' | 'hazard/iogp'
);

CREATE TABLE IF NOT EXISTS report_precursors (
  report_id      INT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  precursor_id   INT NOT NULL REFERENCES precursors(id) ON DELETE CASCADE,
  status         TEXT NOT NULL,   -- PRESENT | AMBIGUOUS | NOT_MENTIONED
  confidence     REAL,
  evidence_count INT,
  PRIMARY KEY (report_id, precursor_id)
);

CREATE TABLE IF NOT EXISTS precursor_evidence (
  id            BIGSERIAL PRIMARY KEY,
  report_id     INT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  precursor_id  INT NOT NULL REFERENCES precursors(id) ON DELETE CASCADE,
  evidence_text TEXT,
  sentence_id   INT,
  polarity      TEXT,             -- 'present' | 'absent'
  FOREIGN KEY (report_id, precursor_id)
    REFERENCES report_precursors(report_id, precursor_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS hazards (
  id   SERIAL PRIMARY KEY,
  code TEXT UNIQUE,
  name TEXT
);
CREATE TABLE IF NOT EXISTS report_hazards (
  report_id INT REFERENCES reports(id) ON DELETE CASCADE,
  hazard_id INT REFERENCES hazards(id) ON DELETE CASCADE,
  evidence  JSONB,
  PRIMARY KEY (report_id, hazard_id)
);

CREATE TABLE IF NOT EXISTS task_types (
  id   SERIAL PRIMARY KEY,
  code TEXT UNIQUE,
  name TEXT
);
CREATE TABLE IF NOT EXISTS report_task_types (
  report_id    INT REFERENCES reports(id) ON DELETE CASCADE,
  task_type_id INT REFERENCES task_types(id) ON DELETE CASCADE,
  evidence     JSONB,
  PRIMARY KEY (report_id, task_type_id)
);

CREATE TABLE IF NOT EXISTS report_work_changes (
  report_id              INT REFERENCES reports(id) ON DELETE CASCADE PRIMARY KEY,
  work_plan_changed       BOOLEAN,
  unexpected_condition    BOOLEAN,
  task_changed            BOOLEAN,
  equipment_changed       BOOLEAN,
  procedure_changed       BOOLEAN,
  work_sequence_changed   BOOLEAN,
  reassessment_performed  BOOLEAN,
  reassessment_missing    BOOLEAN
);

-- ------------------------------------------------------------
-- 3. FEATURE MIRROR   (mirrors the 70-col encoded CSV)
--    -> powers SQL pattern mining with zero string parsing
--    NOTE: precursor columns are code, name, taxonomy = 3 base;
--          the 13 × 3 (status/confidence/count) and risk flags are
--          generated by the ingest tooling from the CSV header.
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS report_features (
  report_id                 INT REFERENCES reports(id) ON DELETE CASCADE PRIMARY KEY,
  -- risk flags from CSV:
  control_failure_present   BOOLEAN,
  missing_control_present   BOOLEAN,
  barrier_failure_present   BOOLEAN,
  control_deviation_present BOOLEAN,
  -- work-change / info-missing flags and report shape land here at runtime.
  report_length             INTEGER,
  sentence_count            INTEGER,
  relevant_sentence_count   INTEGER,
  relevance_ratio           REAL,
  -- full encoded CSV row (13x3 precursor + extra flags) preserved here:
  features                  JSONB
);

-- ------------------------------------------------------------
-- 4. LIFE-SAVING RULES   (IOGP 9 rules)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS life_saving_rules (
  id          SERIAL PRIMARY KEY,
  rule_id     TEXT NOT NULL UNIQUE,   -- LSR01, LSR02, ...
  name        TEXT NOT NULL,
  description TEXT
);

CREATE TABLE IF NOT EXISTS report_life_saving_rules (
  report_id    INT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  lsr_id       INT NOT NULL REFERENCES life_saving_rules(id) ON DELETE CASCADE,
  status       TEXT NOT NULL,          -- BROKEN | NOT_BROKEN | UNCERTAIN | NOT_APPLICABLE
  confidence   REAL,
  reason       TEXT,
  applicable   BOOLEAN,
  PRIMARY KEY (report_id, lsr_id)
);

CREATE TABLE IF NOT EXISTS lsr_evidence (
  id              BIGSERIAL PRIMARY KEY,
  report_id       INT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  lsr_id          INT NOT NULL REFERENCES life_saving_rules(id) ON DELETE CASCADE,
  evidence_text   TEXT,
  sentence_id     INT,
  evidence_type   TEXT,                 -- 'broken' | 'compliance'
  FOREIGN KEY (report_id, lsr_id)
    REFERENCES report_life_saving_rules(report_id, lsr_id) ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- 5. PATTERN INTELLIGENCE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS patterns (
  id            SERIAL PRIMARY KEY,
  title         TEXT,
  description   TEXT,
  pattern_type  TEXT,             -- 'sql_agg' | 'semantic_cluster' | 'combined'
  confidence    REAL,
  severity      TEXT,
  location      TEXT,
  activity      TEXT,
  precursor_id  INT,
  lsr_id        INT,
  report_count  INT,
  sif_count     INT,
  first_detected DATE,
  last_detected  DATE
);
CREATE TABLE IF NOT EXISTS pattern_reports (
  pattern_id INT REFERENCES patterns(id) ON DELETE CASCADE,
  report_id  INT REFERENCES reports(id) ON DELETE CASCADE,
  similarity REAL,
  PRIMARY KEY (pattern_id, report_id)
);

-- ------------------------------------------------------------
-- 6. RECOMMENDATIONS   (always carry evidence)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS recommendations (
  id                SERIAL PRIMARY KEY,
  pattern_id        INT REFERENCES patterns(id) ON DELETE CASCADE,
  barrier_id        INT,
  recommendation    TEXT,
  priority          TEXT,
  intervention_type TEXT,
  confidence        REAL
);
CREATE TABLE IF NOT EXISTS recommendation_evidence (
  id                BIGSERIAL PRIMARY KEY,
  recommendation_id INT REFERENCES recommendations(id) ON DELETE CASCADE,
  evidence_type     TEXT,          -- 'report' | 'kb_document'
  report_id         INT REFERENCES reports(id) ON DELETE CASCADE,
  kb_chunk_id       INT,
  UNIQUE (recommendation_id, evidence_type, report_id, kb_chunk_id)
);

-- ------------------------------------------------------------
-- 7. SAFETY KNOWLEDGE BASE   (RAG citations)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS knowledge_documents (
  id       SERIAL PRIMARY KEY,
  source   TEXT,
  name     TEXT,
  page     INT,
  path     TEXT
);
CREATE TABLE IF NOT EXISTS knowledge_chunks (
  id           SERIAL PRIMARY KEY,
  document_id  INT REFERENCES knowledge_documents(id) ON DELETE CASCADE,
  chunk_text   TEXT,
  metadata     JSONB
);
DO $$ BEGIN
  ALTER TABLE knowledge_chunks ADD COLUMN IF NOT EXISTS embedding VECTOR(384);
EXCEPTION WHEN OTHERS THEN NULL;
END $$;

-- ------------------------------------------------------------
-- 8. AUDIT TRAIL   (model/version -> result)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analysis_runs (
  id             SERIAL PRIMARY KEY,
  report_id      INT REFERENCES reports(id) ON DELETE CASCADE,
  model_name     TEXT,
  model_version  TEXT,
  prompt_version TEXT,
  confidence     REAL,
  ran_at         TIMESTAMPTZ DEFAULT now()
);

-- helpful indices
CREATE INDEX IF NOT EXISTS idx_reports_incident ON reports(incident_id);
CREATE INDEX IF NOT EXISTS idx_reports_date     ON reports(event_date);
CREATE INDEX IF NOT EXISTS idx_precursor_status ON report_precursors(status);
CREATE INDEX IF NOT EXISTS idx_lsr_status ON report_life_saving_rules(status);
CREATE INDEX IF NOT EXISTS idx_pattern_reports_pattern ON pattern_reports(pattern_id);

-- idempotent column migrations for existing installs
ALTER TABLE reports ADD COLUMN IF NOT EXISTS analysis_json JSONB;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS edited_at TIMESTAMPTZ;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS sif_method TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS sif_weight_source TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS sif_components JSONB;
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS lsr_id INT;

-- ------------------------------------------------------------
-- 9. LOCATIONS   (stable coordinate master for map display)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS locations (
  id            SERIAL PRIMARY KEY,
  name          TEXT NOT NULL UNIQUE,
  latitude      REAL,
  longitude     REAL,
  region        TEXT,
  asset_type    TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- link reports to locations (via location_id FK)
ALTER TABLE reports ADD COLUMN IF NOT EXISTS location_id INT REFERENCES locations(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_reports_location_id ON reports(location_id);

-- ------------------------------------------------------------
-- 10. SIF ASSESSMENTS   (from attention model downstream output)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sif_assessments (
  id                SERIAL PRIMARY KEY,
  report_id         INT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  attention_level   TEXT,           -- IMMEDIATE | SHORT_TERM | PLANNED | MONITOR
  urgency_score     REAL,
  risk_potential    REAL,
  systemic_attention TEXT,          -- NONE | LOW | MODERATE | HIGH
  systemic_score    REAL,
  confidence        REAL,
  prediction_mode   TEXT,           -- RULE_BASED_COLD_START | HYBRID_ML
  actions           JSONB,         -- list of action recommendations
  drivers           JSONB,         -- list of driver items
  uncertainty       JSONB,         -- missing info, contradictions, etc.
  barrier_failure_rate REAL,
  model_version     TEXT,
  created_at        TIMESTAMPTZ DEFAULT now(),
  UNIQUE(report_id)
);

-- ------------------------------------------------------------
-- 11. BARRIERS / FAILURE AREAS   (IOGP Life-Saving Rules mapped as barriers)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS barriers (
  id       SERIAL PRIMARY KEY,
  code     TEXT NOT NULL UNIQUE,
  name     TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS report_barriers (
  report_id     INT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  barrier_id    INT NOT NULL REFERENCES barriers(id) ON DELETE CASCADE,
  status        TEXT NOT NULL,   -- BROKEN | NOT_BROKEN | UNCERTAIN | NOT_APPLICABLE
  confidence    REAL,
  reason        TEXT,
  PRIMARY KEY (report_id, barrier_id)
);

-- helpful indices for new tables
CREATE INDEX IF NOT EXISTS idx_sif_assessments_report ON sif_assessments(report_id);
CREATE INDEX IF NOT EXISTS idx_report_barriers_report ON report_barriers(report_id);
CREATE INDEX IF NOT EXISTS idx_locations_name ON locations(name);

-- ============================================================
-- SIF-Aegis v0.4+ extensions: auth, temporal, audit, risk
-- ============================================================

-- ------------------------------------------------------------
-- 12. USERS   (JWT authentication + RBAC)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            SERIAL PRIMARY KEY,
  username      TEXT NOT NULL UNIQUE,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name     TEXT,
  role          TEXT NOT NULL DEFAULT 'HSE_ENGINEER',  -- HSE_ENGINEER | MANAGER | ADMIN
  is_active     BOOLEAN DEFAULT TRUE,
  created_at    TIMESTAMPTZ DEFAULT now(),
  updated_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

-- ------------------------------------------------------------
-- 13. REPORT SUMMARIES   (versioned, admin-editable, separate from raw report)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS report_summaries (
  id            SERIAL PRIMARY KEY,
  report_id     INT NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  summary_text  TEXT NOT NULL,
  summary_type  TEXT NOT NULL DEFAULT 'AI_GENERATED',  -- AI_GENERATED | ADMIN_EDITED
  version       INT NOT NULL DEFAULT 1,
  edited_by     INT REFERENCES users(id),
  edited_at     TIMESTAMPTZ,
  created_at    TIMESTAMPTZ DEFAULT now(),
  is_current    BOOLEAN DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_report_summaries_report ON report_summaries(report_id);
CREATE INDEX IF NOT EXISTS idx_report_summaries_current ON report_summaries(report_id, is_current);

-- ------------------------------------------------------------
-- 14. AUDIT LOG   (append-only, comprehensive)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
  id            BIGSERIAL PRIMARY KEY,
  user_id       INT REFERENCES users(id),
  username      TEXT,
  action        TEXT NOT NULL,        -- summary_edit | analysis_edit | user_role_change | location_change | report_state_change | login
  entity_type   TEXT NOT NULL,        -- report | user | location | pattern | system
  entity_id     TEXT,                 -- incident_id, user_id, etc.
  old_value     JSONB,
  new_value     JSONB,
  ip_address    TEXT,
  created_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_log_entity ON audit_log(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at);

-- ------------------------------------------------------------
-- 15. LOCATION RISK SNAPSHOTS   (historical risk tracking)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS location_risk_snapshots (
  id              SERIAL PRIMARY KEY,
  location_id     INT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
  period_start    DATE NOT NULL,
  period_end      DATE NOT NULL,
  risk_score      REAL NOT NULL,
  risk_level      TEXT NOT NULL,
  sif_count       INT DEFAULT 0,
  report_count    INT DEFAULT 0,
  sif_rate        REAL DEFAULT 0,
  trend           TEXT,              -- INCREASING | DECREASING | STABLE | NEWLY_EMERGING
  calculated_at   TIMESTAMPTZ DEFAULT now(),
  UNIQUE(location_id, period_start, period_end)
);
CREATE INDEX IF NOT EXISTS idx_risk_snapshots_location ON location_risk_snapshots(location_id);
CREATE INDEX IF NOT EXISTS idx_risk_snapshots_period ON location_risk_snapshots(period_start, period_end);

-- ------------------------------------------------------------
-- 16. PROCESSING QUEUE   (background job tracking)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS processing_queue (
  id            SERIAL PRIMARY KEY,
  report_id     INT REFERENCES reports(id) ON DELETE CASCADE,
  job_type      TEXT NOT NULL,        -- nlp_analysis | embedding | pattern_rebuild | risk_recalc
  status        TEXT NOT NULL DEFAULT 'PENDING',  -- PENDING | RUNNING | COMPLETED | FAILED
  error_message TEXT,
  created_at    TIMESTAMPTZ DEFAULT now(),
  started_at    TIMESTAMPTZ,
  completed_at  TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_processing_queue_status ON processing_queue(status);

-- ------------------------------------------------------------
-- 17. REPORT PROCESSING STATE   (track per-report pipeline status)
-- ------------------------------------------------------------
ALTER TABLE reports ADD COLUMN IF NOT EXISTS processing_state TEXT DEFAULT 'PENDING';
ALTER TABLE reports ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMPTZ DEFAULT now();
ALTER TABLE reports ADD COLUMN IF NOT EXISTS report_type TEXT DEFAULT 'OBSERVATION';
ALTER TABLE reports ADD COLUMN IF NOT EXISTS event_time TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS activity TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS work_area TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS equipment TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS work_type TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS unsafe_act TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS unsafe_condition TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS near_miss_details TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS immediate_action TEXT;
ALTER TABLE reports ADD COLUMN IF NOT EXISTS witnesses TEXT;

CREATE INDEX IF NOT EXISTS idx_reports_processing ON reports(processing_state);
CREATE INDEX IF NOT EXISTS idx_reports_type ON reports(report_type);

-- ------------------------------------------------------------
-- 18. PATTERN ENHANCEMENT   (scoring + ranking)
-- ------------------------------------------------------------
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS pattern_score REAL DEFAULT 0;
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS priority_level TEXT DEFAULT 'LOW';
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS sif_rate REAL DEFAULT 0;
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS trend TEXT DEFAULT 'STABLE';
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS lift REAL;
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS dominance REAL;
ALTER TABLE patterns ADD COLUMN IF NOT EXISTS last_recalculated TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_patterns_score ON patterns(pattern_score DESC);
CREATE INDEX IF NOT EXISTS idx_patterns_priority ON patterns(priority_level);

-- ------------------------------------------------------------
-- 19. LOCATION ENHANCEMENT   (risk metadata)
-- ------------------------------------------------------------
ALTER TABLE locations ADD COLUMN IF NOT EXISTS risk_score REAL DEFAULT 0;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS risk_level TEXT DEFAULT 'LOW';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS sif_rate REAL DEFAULT 0;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS trend TEXT DEFAULT 'STABLE';
ALTER TABLE locations ADD COLUMN IF NOT EXISTS last_risk_calculated TIMESTAMPTZ;